platform:
  - Win32
  
environment:  
  CTEST_OUTPUT_ON_FAILURE:
    1
  matrix:
    - PYTHON_DIR: C:\\Python27
      PYTHON_VERSION: 2.7.12
    - PYTHON_DIR: C:\\Python35
      PYTHON_VERSION: 3.5.2
      
configuration: Release

install:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%
  - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - call scripts\install-gmusicapi.bat 

build_script:
  - cmake . -B_build -DPYBIND11_PYTHON_VERSION=%PYTHON_VERSION%
  - cmake --build _build --config %CONFIGURATION% -- -clp:Verbosity=minimal
  
test_script:
  - cmake --build _build --target RUN_TESTS --config %CONFIGURATION% -- -clp:Verbosity=minimal